[JSDoc] Add missing documentation for botbuilder-dialogs/memory/scopes
southworks/botbuilder-js pull request #147
Opened 2020-09-25 21:09 UTC by iscaltritti-sw

Addresses # 2602

## Description
This PR adds all the missing documentation based on the errors thrown for files in the _memory/scopes_ directory of the _botbuilder-dialogs library_.
Some documentation is ported and adapted from [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet)

Note: the `warn` property is replaced with `error` in the last PR of the series adding the documentation to avoid build failures.

## Specific Changes

  - Added JSDoc comments in all methods. 

## Testing
The following image shows the ESLint Report with no JSDoc errors for the updated files.
![image](https://user-images.githubusercontent.com/64803884/94315825-a8f4a900-ff59-11ea-88e1-f48092a252f8.png)

2020-09-28 13:01 UTC, sw-joelmut requested changes

2020-09-28 17:58 UTC, santgr11 commented on libraries/botbuilder-dialogs/src/memory/scopes/botStateMemoryScope.ts
> +     * @param force >Optional, `true` to overwrite any existing state cache;
fixed, thanks

2020-09-29 17:12 UTC, ceciliaavila requested changes

2020-09-29 17:12 UTC, ceciliaavila commented on libraries/botbuilder-dialogs/src/memory/scopes/dialogMemoryScope.ts
> +     * Gets the backing memory for this scope
```suggestion
     * Gets the backing memory for this scope.
```

2020-09-29 17:21 UTC, sw-joelmut approved these changes

2020-09-29 17:23 UTC, ceciliaavila approved these changes

2020-09-30 20:04 UTC, denscollo approved these changes

2020-09-30 20:41 UTC, denscollo commented
Promoted

2020-09-30 20:41 UTC, closed without merging