[JSDoc] Add missing documentation for botbuilder-dialogs/memory
southworks/botbuilder-js pull request #149
Opened 2020-09-25 21:09 UTC by iscaltritti-sw

Addresses # 2602

## Description
This PR adds all the missing documentation based on the errors thrown for files in the _memory_ directory of the _botbuilder-dialogs library_.
Some documentation is ported and adapted from [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet)

Note: the `warn` property is replaced with `error` in the last PR of the series adding the documentation to avoid build failures.

## Specific Changes

  - Added JSDoc comments in all methods. 

## Testing
The following image shows the ESLint Report with no JSDoc errors for the updated files.
![image](https://user-images.githubusercontent.com/64803884/94315855-b742c500-ff59-11ea-9857-b3f4fc25c805.png)

2020-09-28 12:53 UTC, sw-joelmut requested changes

2020-09-28 12:53 UTC, sw-joelmut commented on libraries/botbuilder-dialogs/src/memory/dialogStateManager.ts
> +     * @param path track path to change.
```suggestion
     * @param path Track path to change.
```

2020-09-28 12:53 UTC, sw-joelmut commented on libraries/botbuilder-dialogs/src/memory/dialogStateManager.ts
> +     * @param name name of scope.
```suggestion
     * @param name Name of scope.
```

2020-09-29 17:21 UTC, sw-joelmut approved these changes

2020-09-29 17:23 UTC, ceciliaavila requested changes

2020-09-29 17:23 UTC, ceciliaavila commented on libraries/botbuilder-dialogs/src/memory/dialogStateManager.ts
> +     * Gets the standard dialog state manager configuration.
```suggestion
     * Creates a standard dialog state manager configuration.
```

2020-09-29 18:05 UTC, ceciliaavila approved these changes

2020-09-30 20:05 UTC, denscollo approved these changes

2020-09-30 20:45 UTC, denscollo commented
Promoted

2020-09-30 20:47 UTC, denscollo commented
Promoted

2020-09-30 20:47 UTC, closed without merging