[JSDoc] Add missing documentation for botframework-streaming websocket and payloads folders
southworks/botbuilder-js pull request #151
Opened 2020-09-25 21:14 UTC by sw-joelmut

Addresses # 2602

## Description
This PR introduces the change to `jsdoc/require-jsdoc` in the [.eslintrc.json](https://github.com/microsoft/botbuilder-js/blob/master/.eslintrc.json#L55) file from `warn` to `error` and adds all the missing JSDoc documentation for [botframework-streaming](https://github.com/microsoft/botbuilder-js/tree/master/libraries/botframework-streaming) based on the errors thrown. Some documentation is ported and adapted from [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet)

> **Note:** We divided the work for this library into two PRs to ease the review. PR# 150 contains the rest of the botbuilder fixes.

## Specific Changes

  - Private methods' documentation that does exist on botbuilder-dotnet we added the `@private` tag in the JSDoc comment.
  - Added JSDoc comments in **15 files**.

## Testing
In the following image there is a sneak peek about the ESLint Report with no JSDoc errors.
![image](https://user-images.githubusercontent.com/62260472/94316276-6f706d80-ff5a-11ea-93b6-3afd520d33f6.png)

2020-09-28 17:59 UTC, iscaltritti-sw approved these changes

2020-09-29 17:45 UTC, ceciliaavila requested changes

2020-09-29 17:45 UTC, ceciliaavila commented on libraries/botframework-streaming/src/payloads/payloadAssemblerManager.ts
> +     * @param The Header of the Stream to retrieve.
```suggestion
     * @param header The Header of the Stream to retrieve.

```

2020-09-29 17:45 UTC, ceciliaavila commented on libraries/botframework-streaming/src/payloads/payloadAssemblerManager.ts
> +     * @returns >A `SubscribableStream` of the assembler's payload.
```suggestion
     * @returns A `SubscribableStream` of the assembler's payload.

```

2020-09-29 17:48 UTC, sw-joelmut commented on libraries/botframework-streaming/src/payloads/payloadAssemblerManager.ts
> +     * @returns >A `SubscribableStream` of the assembler's payload.
Resolved all feedback

2020-09-29 17:49 UTC, ceciliaavila approved these changes

2020-09-30 13:09 UTC, santgr11 requested changes

2020-09-30 13:09 UTC, santgr11 commented on libraries/botframework-streaming/src/payloads/payloadAssemblerManager.ts
> +
Fix these spaces

2020-09-30 13:16 UTC, sw-joelmut commented
Thanks @santgr11, feedback applied.

2020-09-30 13:31 UTC, santgr11 approved these changes

2020-09-30 20:14 UTC, denscollo approved these changes

2020-09-30 20:51 UTC, denscollo commented
promoted

2020-09-30 20:51 UTC, closed without merging