[JSDoc] Add missing documentation for botbuilder-lg root files
southworks/botbuilder-js pull request #153
Opened 2020-09-28 17:23 UTC by ceciliaavila

Addresses # 2602

## Description
This PR adds the missing documentation in [botbuilder-lg](https://github.com/microsoft/botbuilder-js/tree/master/libraries/botbuilder-lg) library.
Some documentation is ported and adapted from [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet)

_Note: We divided the work for this library into two PRs to easy their review. The PR#XXXX contains the rest of the botbuilder-lg fixes._

## Specific Changes

- Added JSDoc comments in all public methods and some of the private ones in the following files:
    - analyzer
    - analyzerResult
    - customizedMemory
    - diagnostic
    - errorListener
    - evaluationOptions
    - evaluationTarget
    - evaluator
    - expander
    - extractor
    - lgResource
    - multiLanguageLG

## Testing
The following image shows the ESLint Report with no JSDoc errors for the files updated.
![image](https://user-images.githubusercontent.com/44245136/94465317-1725af80-0196-11eb-8f0f-88deeb87afbb.png)

2020-09-28 18:02 UTC, iscaltritti-sw approved these changes

2020-09-28 18:14 UTC, sw-joelmut requested changes

2020-09-28 18:14 UTC, sw-joelmut commented on libraries/botbuilder-lg/src/extractor.ts
> +     * Extracts the templates and returns a map with their names and bodys.
```suggestion
     * Extracts the templates and returns a map with their names and bodies.
```

2020-09-29 16:54 UTC, ceciliaavila commented on libraries/botbuilder-lg/src/extractor.ts
> +     * Extracts the templates and returns a map with their names and bodys.
Fixed. Thanks!!

2020-09-29 17:20 UTC, sw-joelmut approved these changes

2020-09-30 13:13 UTC, santgr11 approved these changes

2020-09-30 20:18 UTC, denscollo approved these changes

2020-09-30 20:56 UTC, denscollo commented
Promoted

2020-09-30 20:56 UTC, closed without merging