[JSDoc] Add missing documentation for botbuilder-dialogs-declarative files
southworks/botbuilder-js pull request #158
Opened 2020-09-29 19:50 UTC by ceciliaavila

Addresses # 2602

## Description
This PR adds the missing documentation in [botbuilder-dialogs-declarative](https://github.com/microsoft/botbuilder-js/tree/master/libraries/botbuilder-dialogs-declarative) library.
Some documentation is ported and adapted from [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet)

## Specific Changes
- Updated jsdoc/require-jsdoc in .eslintrc.json from warn to error.
- Added JSDoc comments in all public methods and classes.

## Testing
The following image shows the ESLint Report with no JSDoc errors.
![image](https://user-images.githubusercontent.com/44245136/94608492-dbf9ae00-0273-11eb-9e53-3410a8df715a.png)

2020-09-29 20:56 UTC, sw-joelmut requested changes

2020-09-29 20:56 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-declarative/src/pathUtil.ts
> + * A utilities class of file path operations.
```suggestion
 * An utility class for file path operations.
```

2020-09-30 12:29 UTC, ceciliaavila commented on libraries/botbuilder-dialogs-declarative/src/pathUtil.ts
> + * A utilities class of file path operations.
That sounds better. Thanks!

2020-09-30 12:30 UTC, sw-joelmut approved these changes

2020-09-30 13:24 UTC, santgr11 approved these changes

2020-09-30 13:29 UTC, iscaltritti-sw approved these changes

2020-10-01 18:03 UTC, denscollo approved these changes

2020-10-01 18:04 UTC, denscollo commented
Promoted

2020-10-01 18:04 UTC, closed without merging