[JSDoc] Add missing documentation for adaptive-expressions/builtinFuntions files 2/10
southworks/botbuilder-js pull request #162
Opened 2020-09-30 15:37 UTC by ceciliaavila

Addresses # 2602

## Description
This PR adds the missing documentation in [adaptive-expressions/builtinFunctions/](https://github.com/microsoft/botbuilder-js/tree/main/libraries/adaptive-expressions/src/builtinFunctions) files.
Some documentation is ported and adapted from [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet)

## Specific Changes
- Added JSDoc comments in all public methods.
- Added `@private` attribute to private methods.

## Testing
The following image shows the ESLint Report with no JSDoc errors.

2020-09-30 16:23 UTC, santgr11 approved these changes

2020-09-30 18:36 UTC, iscaltritti-sw approved these changes

2020-09-30 19:45 UTC, sw-joelmut requested changes

2020-09-30 19:45 UTC, sw-joelmut commented on libraries/adaptive-expressions/src/builtinFunctions/dateTimeDiff.ts
> +     * Initializes a new instance of the `DataUriToBinary` class.
```suggestion
     * Initializes a new instance of the `DateTimeDiff ` class.

```

2020-09-30 19:51 UTC, ceciliaavila commented on libraries/adaptive-expressions/src/builtinFunctions/dateTimeDiff.ts
> +     * Initializes a new instance of the `DataUriToBinary` class.
Fixed. Thanks!

2020-09-30 19:52 UTC, sw-joelmut approved these changes

2020-10-01 18:32 UTC, denscollo approved these changes

2020-10-01 18:33 UTC, denscollo commented
Only feedback is: The branch name selection could have been better. Promoted

2020-10-01 18:33 UTC, closed without merging