[JSDoc] Add missing documentation for adaptive-expressions/builtinFuntions files 4/10
southworks/botbuilder-js pull request #167
Opened 2020-09-30 17:35 UTC by iscaltritti-sw

Addresses # 2602

## Description
This PR adds the missing documentation in [adaptive-expressions/builtinFunctions/](https://github.com/microsoft/botbuilder-js/tree/main/libraries/adaptive-expressions/src/builtinFunctions) files.
Some documentation is ported and adapted from [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet)

## Specific Changes
- Added JSDoc comments in all public methods.
- Added `@private` attribute to private methods.
- Fixes linter spacing and semicolon warnings.

## Testing
The following image shows the ESLint Report with no JSDoc errors.
![image](https://user-images.githubusercontent.com/64803884/94719612-c777ed00-0329-11eb-8936-ee5df8e7ad6a.png)

2020-09-30 19:44 UTC, ceciliaavila requested changes

2020-09-30 19:44 UTC, ceciliaavila commented on libraries/adaptive-expressions/src/builtinFunctions/if.ts
> +     * Initializes a new instance of the `GreaterThan` class.
```suggestion
     * Initializes a new instance of the `If` class.
```

2020-09-30 19:44 UTC, ceciliaavila commented on libraries/adaptive-expressions/src/builtinFunctions/ignore.ts
> +     * Initializes a new instance of the `GreaterThan` class.
```suggestion
     * Initializes a new instance of the `Ignore` class.
```

2020-09-30 19:46 UTC, iscaltritti-sw commented
Fixed, thanks @ceciliaavila !

2020-09-30 19:50 UTC, sw-joelmut approved these changes

2020-09-30 19:52 UTC, ceciliaavila approved these changes

2020-09-30 21:00 UTC, santgr11 approved these changes

2020-10-01 18:40 UTC, denscollo approved these changes

2020-10-01 18:41 UTC, denscollo commented
Promoted

2020-10-01 18:41 UTC, closed without merging