[JSDoc] Add missing documentation for botbuilder-dialogs-adaptive converters/expressions/generators/luis/selectors folders
southworks/botbuilder-js pull request #176
Opened 2020-09-30 19:21 UTC by sw-joelmut

Addresses # 2602

## Description
This PR adds all the missing JSDoc documentation for [botbuilder-dialogs-adaptive](https://github.com/microsoft/botbuilder-js/tree/master/libraries/botbuilder-dialogs-adaptive) based on the errors thrown. Some documentation is ported and adapted from [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet)

We divided the work for this library into multiple PRs to ease the review.

** PR LIST **

## Specific Changes

- Ported documentation from botbuilder-dotnet
- Added `@private` for private methods.
- Added JSDoc comments in **15 files**.

## Testing
In the following image there is a sneak peek about the ESLint Report with no JSDoc errors.
![image](https://user-images.githubusercontent.com/62260472/94729966-e336bf80-0338-11eb-815d-d4271eae5219.png)

2020-09-30 19:48 UTC, iscaltritti-sw approved these changes

2020-09-30 19:48 UTC, iscaltritti-sw commented on libraries/botbuilder-dialogs-adaptive/src/selectors/firstSelector.ts
> +     * @param evaluate True if rules should be evaluated on select.
```suggestion
     * @param evaluate `true` if rules should be evaluated on select.
```
A readability improvement.

2020-09-30 19:48 UTC, iscaltritti-sw commented on libraries/botbuilder-dialogs-adaptive/src/selectors/randomSelector.ts
> +     * @param evaluate True if rules should be evaluated on select.
```suggestion
     * @param evaluate `true` if rules should be evaluated on select.
```

Same.

2020-09-30 20:39 UTC, santgr11 commented on libraries/botbuilder-dialogs-adaptive/src/generators/templateEngineLanguageGenerator.ts
> +     * @param arg1 An LG `Templates` or a `Resource`.
Should we clarify that these args are optional?

2020-09-30 20:40 UTC, santgr11 commented on libraries/botbuilder-dialogs-adaptive/src/luis/luisAdaptiveRecognizer.ts
> +     * @param telemetryMetrics Additional metrics to be logged to telemetry with event.
same here with `telemetryMetrics`

2020-09-30 21:06 UTC, ceciliaavila requested changes

2020-10-01 12:56 UTC, sw-joelmut commented
@ceciliaavila @santgr11 @iscaltritti-sw, feedback applied, thanks.

2020-10-01 13:00 UTC, santgr11 approved these changes

2020-10-01 13:12 UTC, ceciliaavila approved these changes

2020-10-01 19:13 UTC, denscollo approved these changes

2020-10-01 19:14 UTC, denscollo commented
Promoted

2020-10-01 19:14 UTC, closed without merging