[JSDoc] Add missing documentation for botbuilder-dialogs-adaptive input folder
southworks/botbuilder-js pull request #177
Opened 2020-10-01 13:00 UTC by sw-joelmut

Addresses # 2602

## Description
This PR adds all the missing JSDoc documentation for [botbuilder-dialogs-adaptive](https://github.com/microsoft/botbuilder-js/tree/master/libraries/botbuilder-dialogs-adaptive) based on the errors thrown. Some documentation is ported and adapted from [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet).

## Specific Changes

- Ported documentation from botbuilder-dotnet
- Added `@private` for private methods.
- Added `@protected` for private methods.
- Added JSDoc comments in **10 files**.

## Testing
In the following image there is a sneak peek about the ESLint Report with no JSDoc errors.
![image](https://user-images.githubusercontent.com/62260472/94812261-e2e80400-03cc-11eb-955f-0efa3a97cc0b.png)

2020-10-01 13:40 UTC, santgr11 requested changes

2020-10-01 13:40 UTC, santgr11 commented on libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts
> +     * Called when input has been received, recognices choice.
```suggestion
     * Called when the input has been received, recognizes choice.
```

2020-10-01 15:37 UTC, ceciliaavila requested changes

2020-10-01 18:02 UTC, sw-joelmut commented
@santgr11 @ceciliaavila, feedback applied, thanks.

2020-10-01 18:03 UTC, iscaltritti-sw approved these changes

2020-10-01 18:04 UTC, ceciliaavila approved these changes

2020-10-01 18:33 UTC, santgr11 approved these changes

2020-10-14 16:32 UTC, ceciliaavila requested changes

2020-10-14 16:32 UTC, ceciliaavila commented on libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts
> +     * @param event [DialogReason](xref:botbuilder-dialogs.DialogReason), the event being raised.
```suggestion
     * @param event [DialogEvent](xref:botbuilder-dialogs.DialogEvent), the event being raised.
```

2020-10-14 17:11 UTC, sw-joelmut reviewed
Changes

2020-10-14 17:11 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts
>       * Called when the dialog is started and pushed onto the dialog stack.
Should we use the Dialog class reference here?, more lines with this point on this file.

2020-10-14 17:11 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-adaptive/src/input/oauthInput.ts
>       * Called when a prompt dialog is pushed onto the dialog stack and is being activated.
Should we use the Dialog class reference here?, more lines with this point on this file.

2020-10-19 17:36 UTC, denscollo commented
@sw-joelmut @ceciliaavila what is the status of this PR? I see that there're changes request, and comments left

2020-10-19 17:39 UTC, sw-joelmut commented
> 
> 
> @sw-joelmut @ceciliaavila what is the status of this PR? I see that there're changes request, and comments left

I'll take a look

2020-10-19 17:51 UTC, sw-joelmut commented
@ceciliaavila @denscollo @iscaltritti-sw feedback applied, thanks.

2020-10-19 17:56 UTC, ceciliaavila approved these changes

2020-10-19 21:19 UTC, denscollo commented
Promoted

2020-10-19 21:19 UTC, closed without merging