[JSDoc] Add missing documentation for botbuilder-dialogs-adaptive entityRecognizers folder
southworks/botbuilder-js pull request #178
Opened 2020-10-01 14:33 UTC by sw-joelmut

Addresses # 2602

## Description
This PR adds all the missing JSDoc documentation for [botbuilder-dialogs-adaptive](https://github.com/microsoft/botbuilder-js/tree/master/libraries/botbuilder-dialogs-adaptive) based on the errors thrown. Some documentation is ported and adapted from [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet)

## Specific Changes

- Ported documentation from botbuilder-dotnet
- Added documentation for the files inside `recognizers/entityRecognizers` folder.
- Added `@protected` for protected methods.
- Added JSDoc comments in **20 files**.

## Testing
In the following image there is a sneak peek about the ESLint Report with no JSDoc errors.
![image](https://user-images.githubusercontent.com/62260472/94822828-79babd80-03d9-11eb-9428-10c7118c3a7c.png)

2020-10-01 14:50 UTC, santgr11 approved these changes

2020-10-01 16:12 UTC, iscaltritti-sw approved these changes

2020-10-01 16:29 UTC, ceciliaavila requested changes

2020-10-01 16:29 UTC, ceciliaavila commented on libraries/botbuilder-dialogs-adaptive/src/recognizers/entityRecognizers/textEntityRecognizer.ts
> + * TextEntityRecognizer - base class for `text.recogizers` from the text recognizer library.
```suggestion
 * TextEntityRecognizer - base class for `text.recognizers` from the text recognizer library.
```

2020-10-01 18:05 UTC, sw-joelmut commented
@ceciliaavila, feedback applied, thanks.

2020-10-01 18:44 UTC, ceciliaavila approved these changes

2020-10-14 15:42 UTC, iscaltritti-sw approved these changes

2020-10-14 18:30 UTC, ceciliaavila approved these changes

2020-10-14 19:00 UTC, denscollo approved these changes

2020-10-19 17:59 UTC, denscollo commented
Promoted

2020-10-19 17:59 UTC, closed without merging