[JSDoc] Add missing documentation for botbuilder-dialogs-adaptive recognizers folder's root
southworks/botbuilder-js pull request #179
Opened 2020-10-01 15:15 UTC by sw-joelmut

Addresses # 2602

## Description
This PR adds all the missing JSDoc documentation for [botbuilder-dialogs-adaptive](https://github.com/microsoft/botbuilder-js/tree/main/libraries/botbuilder-dialogs-adaptive) based on the errors thrown. Some documentation is ported and adapted from [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet)

## Specific Changes

- Ported documentation from botbuilder-dotnet
- Added documentation for the files inside `recognizers` folder's root.
- Added `@private` for private methods.
- Added `@protected` for protected methods.
- Added JSDoc comments in **6 files**.

## Testing
In the following image there is a sneak peek about the ESLint Report with no JSDoc errors.
![image](https://user-images.githubusercontent.com/62260472/94828188-99ed7b00-03df-11eb-8c56-4f0dae47d993.png)

2020-10-01 16:34 UTC, ceciliaavila requested changes

2020-10-01 16:34 UTC, ceciliaavila commented on libraries/botbuilder-dialogs-adaptive/src/recognizers/intentPattern.ts
> +     * Converts an object or string to a `IntentPattern` instance.
```suggestion
     * Converts an object or string to an `IntentPattern` instance.
```

2020-10-01 16:34 UTC, ceciliaavila commented on libraries/botbuilder-dialogs-adaptive/src/recognizers/recognizerSet.ts
> + * RecognizerSet - Recognizer which is the union of of multiple recognizers into one RecognizerResult.
```suggestion
 * RecognizerSet - Recognizer which is the union of multiple recognizers into one RecognizerResult.
```

2020-10-01 18:08 UTC, sw-joelmut commented
@ceciliaavila feedback applied, thanks

2020-10-01 18:09 UTC, iscaltritti-sw approved these changes

2020-10-01 18:44 UTC, ceciliaavila approved these changes

2020-10-14 15:42 UTC, iscaltritti-sw approved these changes

2020-10-14 18:32 UTC, ceciliaavila approved these changes

2020-10-14 19:05 UTC, denscollo approved these changes

2020-10-19 21:35 UTC, denscollo commented
promoted

2020-10-19 21:35 UTC, closed without merging