[JSDoc] Add missing documentation for botbuilder-dialogs-adaptive conditions folder 2/2
southworks/botbuilder-js pull request #184
Opened 2020-10-01 17:35 UTC by sw-joelmut

Addresses # 2602

## Description
This PR adds all the missing JSDoc documentation for [botbuilder-dialogs-adaptive](https://github.com/microsoft/botbuilder-js/tree/master/libraries/botbuilder-dialogs-adaptive) based on the errors thrown. Some documentation is ported and adapted from [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet)

## Specific Changes

- Ported documentation from botbuilder-dotnet
- Added documentation for the files inside `conditions` folder.
- Added `@protected` for protected methods.
- Added JSDoc comments in **12 files**.

## Testing
In the following image there is a sneak peek about the ESLint Report with no JSDoc errors.
![image](https://user-images.githubusercontent.com/62260472/94843628-58ff6180-03f3-11eb-8362-8fb1658eebb8.png)

2020-10-01 17:52 UTC, iscaltritti-sw approved these changes

2020-10-01 20:03 UTC, santgr11 approved these changes

2020-10-02 12:27 UTC, ceciliaavila requested changes

2020-10-02 12:27 UTC, ceciliaavila commented on libraries/botbuilder-dialogs-adaptive/src/conditions/onError.ts
> +     * Initializes a new instance of the `OnEndOfConversationActivity` class.
```suggestion
     * Initializes a new instance of the `OnError` class.
```

2020-10-02 12:30 UTC, sw-joelmut commented
@ceciliaavila, feedback applied, thanks

2020-10-02 12:30 UTC, ceciliaavila approved these changes

2020-10-14 15:43 UTC, iscaltritti-sw approved these changes

2020-10-14 19:09 UTC, denscollo approved these changes

2020-10-14 19:12 UTC, ceciliaavila approved these changes

2020-10-20 21:04 UTC, denscollo commented
Promoted

2020-10-20 21:04 UTC, closed without merging