[JSDoc] Add mising documentation for botbuilder-testing
southworks/botbuilder-js pull request #185
Opened 2020-10-02 13:14 UTC by sw-joelmut

Addresses # 2602

## Description
This PR adds all the missing JSDoc documentation for [botbuilder-testing](https://github.com/microsoft/botbuilder-js/tree/master/libraries/botbuilder-testing) based on the errors thrown. Some documentation is ported and adapted from [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet).

## Specific Changes

- Ported documentation from botbuilder-dotnet
- Added `@private` for private methods.
- Added JSDoc comments in **2 files**.

## Testing
In the following image there is a sneak peek about the ESLint Report with no JSDoc errors.
![image](https://user-images.githubusercontent.com/62260472/94926715-91f11200-0497-11eb-80fd-b11e83c22b0c.png)

2020-10-02 14:21 UTC, santgr11 approved these changes
Since all the comments we are adding in the rest of PRs are using `Optional,` instead of `(Optional)` I would like to change these to be the same as the rest, but I'm not sure if this is the proper approach since this comment is one that already existed that is being copied to the overloads.

The rest lgtm

2020-10-02 14:22 UTC, sw-joelmut commented
@santgr11 , fixed, thanks

2020-10-02 16:03 UTC, iscaltritti-sw approved these changes

2020-10-02 16:30 UTC, ceciliaavila requested changes

2020-10-02 16:30 UTC, ceciliaavila commented on libraries/botbuilder-testing/src/dialogTestClient.ts
> +     * @param middlewares Optional. The test adapter to use. If this parameter is not provided, the test client will use a default TestAdapter.
The descriptions of testAdapter and middlewares are mixed.

2020-10-02 16:30 UTC, ceciliaavila commented on libraries/botbuilder-testing/src/dialogTestClient.ts
> +     * @param middlewares Optional. The test adapter to use. If this parameter is not provided, the test client will use a default TestAdapter.
Same in here.

2020-10-02 18:16 UTC, sw-joelmut commented
@ceciliaavila, feedback applied, thanks

2020-10-02 18:18 UTC, ceciliaavila approved these changes

2020-10-14 15:43 UTC, iscaltritti-sw approved these changes

2020-10-14 19:09 UTC, denscollo approved these changes

2020-10-14 19:13 UTC, ceciliaavila approved these changes

2020-10-19 21:41 UTC, denscollo commented
Promoted

2020-10-19 21:41 UTC, closed without merging