[internal] Apply xref links for southworks/add/jsdoc/botbuilder-lg
southworks/botbuilder-js pull request #192
Opened 2020-10-09 20:27 UTC by iscaltritti-sw

PR 2830 in MS, #155 in SW

Feedback applied to use xref to link to other methods and missing documentation instances.

Changes requested for `Template` don't apply to our additions.
There's also one question regarding our C# port convention for private methods. The method `expressionParser` is documented for C#, so we ported it.

note that the links will not work in visual studio, these links are meant to be used to build the web documentation.
searchable here https://docs.microsoft.com/en-us/javascript/api/

This PR doesn't have conflicts, I didn't update the branch with main here to don't bring irrelevant changes.

2020-10-13 12:57 UTC, ceciliaavila requested changes

2020-10-13 12:57 UTC, ceciliaavila commented on libraries/botbuilder-lg/src/sourceRange.ts
> +     * @param parseTree `ParserRuleContext`. Rule invocation record for parsing.
Here there's a ref missing.

2020-10-13 12:57 UTC, ceciliaavila commented on libraries/botbuilder-lg/src/sourceRange.ts
> +     * @param x [Range](xref:botbuilder-lg.Range) of block or `ParserRuleContext`, rule invocation record for parsing.
Same in here with ParserRuleContext

2020-10-13 13:03 UTC, sw-joelmut approved these changes

2020-10-13 13:18 UTC, ceciliaavila approved these changes

2020-10-13 13:31 UTC, santgr11 approved these changes

2020-10-13 18:06 UTC, sw-joelmut approved these changes

2020-10-14 19:24 UTC, denscollo approved these changes

2020-10-14 19:24 UTC, denscollo approved these changes

2020-10-14 19:27 UTC, merged