[internal] Apply xref links for botframework-streaming-websocket
southworks/botbuilder-js pull request #212
Opened 2020-10-13 19:26 UTC by santgr11

PR 2825 in MS, #151 in SW

Feedback applied to use xref to link to other methods.

note that the links will not work in visual studio, these links are meant to be used to build the web documentation.
searchable here https://docs.microsoft.com/en-us/javascript/api/

This PR doesn't include the conflict resolution.

2020-10-13 20:07 UTC, ceciliaavila requested changes

2020-10-13 20:18 UTC, santgr11 commented on libraries/botframework-streaming/src/payloads/requestManager.ts
> +     * @param response The [ReceiveResponse](xref:botframework-streaming.IReceiveResponse) in response to the request.
The response must be `IReceiveResponse`, but the comment says `ReceiveResponse`, I wasn't sure about this one. Do you think we should change the `ReceiveResponse` to `IReceiveResponse`?

2020-10-13 20:21 UTC, ceciliaavila commented on libraries/botframework-streaming/src/payloads/requestManager.ts
> +     * @param response The [ReceiveResponse](xref:botframework-streaming.IReceiveResponse) in response to the request.
Yes, I think they should match.

2020-10-13 21:04 UTC, santgr11 commented on libraries/botframework-streaming/src/payloads/requestManager.ts
> +     * @param response The [ReceiveResponse](xref:botframework-streaming.IReceiveResponse) in response to the request.
changed

2020-10-13 21:05 UTC, ceciliaavila approved these changes

2020-10-14 12:03 UTC, iscaltritti-sw approved these changes

2020-10-14 19:40 UTC, denscollo approved these changes

2020-10-14 19:40 UTC, merged