[internal] Apply xref links for southworks/add/jsdoc/botbuilder-skills
southworks/botbuilder-js pull request #216
Opened 2020-10-13 20:06 UTC by iscaltritti-sw

PR 2818 in MS, #143 in SW

Feedback applied to use xref to link to other methods.

note that the links will not work in visual studio, these links are meant to be used to build the web documentation.
searchable here https://docs.microsoft.com/en-us/javascript/api/

This PR doesn't have conflicts, I didn't update the branch with main here to don't bring irrelevant changes.

2020-10-13 20:19 UTC, ceciliaavila requested changes

2020-10-13 20:19 UTC, ceciliaavila commented on libraries/botbuilder/src/channelServiceHandler.ts
> +     * @returns A `Promise` representation of for the operation.
```suggestion
     * @returns A `Promise` representation for the operation.
```

2020-10-13 20:19 UTC, ceciliaavila commented on libraries/botbuilder/src/channelServiceHandler.ts
> +     * @returns A `Promise` representation of for the operation.
```suggestion
     * @returns A `Promise` representation for the operation.
```

2020-10-13 20:19 UTC, ceciliaavila commented on libraries/botbuilder/src/skills/skillHttpClient.ts
> +     * @param callbackUrlOrActivity The callback Url for the skill host or the the [Activity](xref:botframework-schema.Activity) to send.
```suggestion
     * @param callbackUrlOrActivity The callback Url for the skill host or the [Activity](xref:botframework-schema.Activity) to send.
```

2020-10-14 12:39 UTC, sw-joelmut approved these changes
Besides Ceci's comments, all good

2020-10-14 13:02 UTC, iscaltritti-sw commented
Corrected, thanks @ceciliaavila!

2020-10-14 13:06 UTC, ceciliaavila approved these changes

2020-10-14 19:32 UTC, santgr11 approved these changes

2020-10-14 19:43 UTC, denscollo approved these changes

2020-10-14 19:44 UTC, merged