port: [#4006] Add TelemetryLoggerConstants for adaptive. (#6029)
southworks/botbuilder-js pull request #240
Opened 2021-12-29 13:19 UTC by sw-joelmut

Fixes # 4006

## Description
This PR adds the `TelemetryLoggerConstants` class and updates all the hard-coded string references to use the property that corresponds. These changes are ported from `DotNet`.

## Specific Changes
- Adds the `TelemetryLoggerConstants` class.
- Updates all the hard-coded strings to use each specific property declared in the `TelemetryLoggerConstants` class, including unit tests.
- Updated the `beginSkill` to use the constant that corresponds with no addition of a new context property, since this case does not exist in DotNet's port.

## Testing
The following images show an overview of the project building correctly to execute the tests successfully.
![imagen](https://user-images.githubusercontent.com/62260472/147666369-aed4fe8a-b683-46d4-975a-952e37b42dd6.png)

2021-12-29 14:16 UTC, ceciliaavila requested changes

2021-12-29 14:16 UTC, ceciliaavila commented on libraries/botbuilder-dialogs-adaptive/src/telemetryLoggerConstants.ts
> +     * The generic name of the event when an binding completes. When this event is logged, the context property will contain a more descriptive constant.
```suggestion
     * The generic name of the event when a binding completes. When this event is logged, the context property will contain a more descriptive constant.
```

2021-12-29 14:54 UTC, ceciliaavila approved these changes

2021-12-29 17:58 UTC, NahuelPerales approved these changes

2021-12-30 13:17 UTC, sw-joelmut commented
Promoted `https://github.com/microsoft/botbuilder-js/pull/4033`

2021-12-30 13:17 UTC, closed without merging