[#2745] Fix current eslint warnings - botbuilder-dialogs-adaptive library - recognizers
southworks/botbuilder-js pull request #251
Opened 2022-01-17 19:07 UTC by NahuelPerales

Adresses # 2745
#minor

## Description
When reviewing the botbuilder-js project it was found that eslint is showing several warnings for the botbuilder-dialogs-adaptive library.

## Specific Changes

- Replaced strings quotes with the correct one depending of the case
- Replaced hasOwnProperty with Object.prototype.hasOwnProperty.call
- Adjusted formatting
- Limited importing scopes
- Added missing jsdocs documentation for parameters and returns for functions
- Removed unused variables

## Testing
Eslint with no warnings and tests passed
![image](https://user-images.githubusercontent.com/94375175/149823185-f518820c-91ba-4cdc-9776-3e7434225438.png)

2022-01-18 21:38 UTC, JuanAr approved these changes
LGTM

2022-01-19 14:19 UTC, sw-joelmut requested changes

2022-01-19 14:19 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-adaptive/src/recognizers/entityRecognizers/regexEntityRecognizer.ts
>  export class RegexEntityRecognizer extends TextEntityRecognizer implements RegexEntityRecognizerConfiguration {
Should have a description

2022-01-19 14:19 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-adaptive/src/recognizers/entityRecognizers/textEntityRecognizer.ts
> + */
Should have a description

2022-01-19 14:19 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-adaptive/src/recognizers/intentPattern.ts
> +     * @returns An instance of regexp with the given pattern.
```suggestion
     * @returns An instance of RegExp with the given pattern.
```

2022-01-19 14:19 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-adaptive/src/recognizers/intentPattern.ts
> +     */
Should have the `Gets the intent.` description

2022-01-19 14:19 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-adaptive/src/recognizers/intentPattern.ts
> +     */
Should have the `Gets the pattern.` description

2022-01-19 14:19 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-adaptive/src/recognizers/multiLanguageRecognizer.ts
> + */
Should have a description

2022-01-19 14:19 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-adaptive/src/recognizers/multiLanguageRecognizer.ts
> +     */
Dont invent new descriptions, use the ones from DotNet, also it doesnt have a description
![imagen](https://user-images.githubusercontent.com/62260472/150148545-ea4a632a-a422-47b9-ac62-32d5c6e68c35.png)

2022-01-19 14:19 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-adaptive/src/recognizers/recognizerSet.ts
> +     */
Same here

2022-01-19 14:19 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-adaptive/src/recognizers/regexRecognizer.ts
> + */
Should have a description

2022-01-19 14:19 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-adaptive/src/recognizers/regexRecognizer.ts
> +     */
Same here

2022-01-19 14:19 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-adaptive/src/recognizers/valueRecognizer.ts
> + */
Should have a description

2022-01-19 14:19 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-adaptive/src/recognizers/valueRecognizer.ts
> +     */
Same here

2022-01-20 15:44 UTC, sw-joelmut approved these changes

2022-01-20 19:46 UTC, sw-joelmut commented
Promoted `https://github.com/microsoft/botbuilder-js/pull/4067`

2022-01-20 19:46 UTC, closed without merging