[#2745] Fix current eslint warnings - botbuilder-dialogs-adaptive library - misc
southworks/botbuilder-js pull request #252
Opened 2022-01-17 19:09 UTC by NahuelPerales

Adresses # 2745
#minor

## Description
When reviewing the botbuilder-js project it was found that eslint is showing several warnings for the botbuilder-dialogs-adaptive library.

## Specific Changes

- Replaced strings quotes with the correct one depending of the case
- Replaced hasOwnProperty with Object.prototype.hasOwnProperty.call
- Adjusted formatting
- Limited importing scopes
- Added missing jsdocs documentation for parameters and returns for functions
- Removed unused variables

## Testing
Eslint with no warnings and tests passed
![image](https://user-images.githubusercontent.com/94375175/149823185-f518820c-91ba-4cdc-9776-3e7434225438.png)

2022-01-18 20:33 UTC, JuanAr commented on libraries/botbuilder-dialogs-adaptive/src/functions/hasPendingActionsFunction.ts
> +    private static function(expression: Expression, state: MemoryInterface, _options: Options): ValueWithError {
I'm not sure why this param is renamed. There might be a good reason.

2022-01-18 20:34 UTC, JuanAr commented on libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts
> +    public async resumeDialog(dc: DialogContext, _reason: DialogReason, _result?: any): Promise<DialogTurnResult> {
I realized that, unused params are prefixed with underscore. Is this a ESLint rule?

2022-01-18 20:35 UTC, JuanAr reviewed
I left some comments, not request changes, because there might be good reasons to for those.

2022-01-18 20:35 UTC, JuanAr commented on libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts
> +    protected onInitializeOptions(_dc: DialogContext, options: any): Promise<any> {
same

2022-01-18 20:35 UTC, JuanAr commented on libraries/botbuilder-dialogs-adaptive/src/input/oauthInput.ts
> +    protected onRecognizeInput(_dc: DialogContext): Promise<InputState> {
same

2022-01-18 21:37 UTC, JuanAr approved these changes
LGTM

2022-01-19 16:55 UTC, sw-joelmut requested changes

2022-01-19 16:55 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-adaptive/src/selectors/mostSpecificSelector.ts
> + */
same

2022-01-19 16:55 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-adaptive/src/templates/staticActivityTemplate.ts
> +     */
For this case i think is valid that doesnt have a description, it gets inherited from the Configurable abstract class, we should do the same for the getConverter method

2022-01-20 16:15 UTC, sw-joelmut approved these changes

2022-01-20 19:48 UTC, sw-joelmut commented
Promoted `https://github.com/microsoft/botbuilder-js/pull/4068`

2022-01-20 19:48 UTC, closed without merging