port: [#4062] Log BadRequest in adapter (#6135)
southworks/botbuilder-js pull request #265
Opened 2022-03-10 14:10 UTC by mraitersw

Fixes # 4062
#minor

## Description
Add warn logger when the activity hasn't a type.

## Specific Changes

  - Added in the common function, between botFrameworkAdapter and cloudAdapater, that validate the actity type.
  
## Tests
![image](https://user-images.githubusercontent.com/97895605/157874062-bd1981c9-1ec9-44c5-b7ee-c3b4b4718e10.png)

2022-03-10 20:01 UTC, ceciliaavila requested changes
I think this should be in cloudAdapter.ts, line 130.
Here we are already throwing a descriptive error.

2022-03-11 12:49 UTC, ceciliaavila requested changes

2022-03-11 12:49 UTC, ceciliaavila commented on libraries/botbuilder/src/botFrameworkAdapter.ts
> +
I'm not sure of adding this here. In case of an error in parseRequest, would this code be reached?

2022-03-11 13:16 UTC, ceciliaavila approved these changes

2022-03-11 15:24 UTC, FedericoBernal approved these changes

2022-03-11 18:13 UTC, ceciliaavila commented
Promoted to MS in PR# 4155

2022-03-11 18:13 UTC, closed without merging