[#4204] Fix remaining eslint warnings - botbuilder-lg
southworks/botbuilder-js pull request #299
Opened 2022-05-02 15:20 UTC by erquirogasw

Addresses # 4204
#minor

## Description
This PR fixes the ESLint and JSDoc issues in the botbuilder-lg library.

## Specific Changes
- Applied auto-fixes with yarn lint --fix.
	- Add trailing commas
	- Fix spacing.
	- Fix indentation.
	- Add blank line in between comments.
	- Fix quoting.
	- Replace arrow functions: () => with function ().
	- Replace let with const.
- Applied manual fixes for:
	- Missing documentation.
	- Unused parameters and imports.
	- Replacing hasOwnProperty calls.
	- Fixing lodash imports.

## Testing
<img width="151" alt="image" src="https://user-images.githubusercontent.com/64815358/166258887-d4d4a601-13f9-46f6-afd3-f0b84bbd98bf.png">

<img width="290" alt="image" src="https://user-images.githubusercontent.com/64815358/166258615-6eaebe0e-85b2-4dab-bfaf-178458c25cca.png">

2022-05-02 21:01 UTC, ceciliaavila requested changes
Also see why the test:compat check is failing.

2022-05-02 21:01 UTC, ceciliaavila commented on libraries/botbuilder-lg/tsconfig.json
> +    "skipLibCheck": true,
Is this change necessary?

2022-05-02 21:01 UTC, ceciliaavila commented on package.json
> +    "lint": "wsrun -m -l lint",
Don't change this until the last PR.

2022-05-02 21:01 UTC, ceciliaavila commented on yarn.lock
> +chromedriver@^100.0.0:
I think there's no need to commit this change.

2022-05-03 12:58 UTC, sw-joelmut requested changes
The changes in yarn.lock, package.json, tsconfig.json and .eslintrc.json should not be required

2022-05-03 12:58 UTC, sw-joelmut commented on libraries/botbuilder-lg/src/evaluator.ts
> +     * @returns the visitor result
```suggestion
     * @returns The visitor result.
```

2022-05-03 12:58 UTC, sw-joelmut commented on libraries/botbuilder-lg/src/expander.ts
> +        // expressionParser: Given expression parser.
Why this comment is necessary?

2022-05-03 12:58 UTC, sw-joelmut commented on libraries/botbuilder-lg/src/expander.ts
> +     * @returns The result of visiting if-else body
```suggestion
     * @returns The result of visiting if-else body.
```

2022-05-03 12:58 UTC, sw-joelmut commented on libraries/botbuilder-lg/src/expander.ts
> +     * @returns The result of visiting NormalTemplateString
```suggestion
     * @returns The result of visiting NormalTemplateString.
```

2022-05-03 12:58 UTC, sw-joelmut commented on libraries/botbuilder-lg/src/templateExtensions.ts
> +     * @returns true if the value is pure Expression, false otherwise.
Start with uppercase and finish with a dot, multiple cases in others

2022-05-05 14:10 UTC, erquirogasw commented on libraries/botbuilder-lg/tsconfig.json
> +    "rootDir": "src"
<img width="379" alt="image" src="https://user-images.githubusercontent.com/64815358/166941711-53f17c51-7376-4b38-92a4-358d1453678b.png">

I'm seeing the setting in the branch. I'll review in git.

2022-05-06 14:25 UTC, sw-joelmut approved these changes

2022-05-06 14:26 UTC, erquirogasw commented
@ceciliaavila Feedback applied. Thanks!

2022-05-06 18:03 UTC, ceciliaavila approved these changes

2022-05-12 16:36 UTC, sw-joelmut commented
/promoted 4235

2022-05-12 16:36 UTC, closed without merging