[#4204] Fix remaining eslint warnings - Rest of botbuilder-dialogs libraries - botbuilder adaptive testing
southworks/botbuilder-js pull request #302
Opened 2022-05-03 21:03 UTC by erquirogasw

Addresses [4204](https://github.com/microsoft/botbuilder-js/issues/4204)
#minor

## Description
This PR fixes the ESLint and JSDoc issues in the botbuilder-dialogs-adaptive-testing library.

## Specific Changes
-Applied auto-fixes with yarn lint --fix
        - Add trailing commas
	- Fix spacing
	- Fix indentation
	- Add blank line in between comments
	- Fix quoting
- Applied manual fixes for:
	- Missing documentation.
	- Unused parameters and imports
	- Disabling detect-non-literal-fs-filename rule to allow dynamic path for files
	- Disabling no-constant-condition rule to allow while (true) loop

## Testing
_Eslint and tests status_

<img width="163" alt="image" src="https://user-images.githubusercontent.com/64815358/166565779-1ac5b488-5be7-4b57-8aae-59b5b17f704d.png">
<img width="156" alt="image" src="https://user-images.githubusercontent.com/64815358/166565804-676da222-85cc-4451-b54b-05ff8ffa21b8.png">

2022-05-05 17:33 UTC, ceciliaavila commented on libraries/botbuilder-dialogs-adaptive-testing/src/actions/assertCondition.ts
> +/* eslint-disable @typescript-eslint/ban-types */
You should have the .eslintrc.json file with this configuration to disable these rules in all the libraries.
![image](https://user-images.githubusercontent.com/44245136/166980219-e72c57cf-79f2-43a7-a4da-ea12985d3d08.png)

2022-05-05 17:58 UTC, erquirogasw commented on libraries/botbuilder-dialogs-adaptive-testing/src/testTelemetryClient.ts
> +    constructor(_settings?: unknown) {
Because I think unknown is a more secure type. Should I leave the type to Any? Or disable it globally?

2022-05-06 17:59 UTC, sw-joelmut approved these changes

2022-05-06 18:15 UTC, ceciliaavila requested changes

2022-05-06 18:15 UTC, ceciliaavila commented on libraries/botbuilder-dialogs-adaptive-testing/src/mocks/mockHttpRequestMiddleware.ts
> +     * @param context The content oject for this turn.
```suggestion
     * @param context The context object for this turn.
```

2022-05-12 15:26 UTC, ceciliaavila approved these changes

2022-05-12 16:38 UTC, sw-joelmut commented
/promoted 4237

2022-05-12 16:38 UTC, closed without merging