fix: [#4204] Fix remaining eslint warnings - Rest of botbuilder-dialogs libraries - adaptive runtime
southworks/botbuilder-js pull request #304
Opened 2022-05-04 17:30 UTC by erquirogasw

Addresses # 4204
#minor

## Description
This PR fixes the ESLint and JSDoc issues in the botbuilder-dialogs-adaptive-runtime library.

## Specific Changes
- Applied auto-fixes with yarn lint --fix
	- Fix spacing
	- Fix indentation
	- Add blank line in between comments
- Applied manual fixes for:
	- Missing documentation

## Testing
_Library eslint status_
![Screenshot 2022-05-04 141033](https://user-images.githubusercontent.com/64815358/166745180-0d0cf63e-25cb-4965-be4a-5cfb15ecdc3b.jpg)

_Library tests status_
![Screenshot 2022-05-04 141015](https://user-images.githubusercontent.com/64815358/166745193-02ab949f-7f69-41d8-8508-7dad28e0691f.jpg)

2022-05-05 12:57 UTC, ceciliaavila requested changes

2022-05-05 12:57 UTC, ceciliaavila commented on libraries/botbuilder-dialogs-adaptive-runtime/src/coreBotAdapter.ts
> + *An adapter that implements the Core Bot and can be hosted in different cloud environments both public and private.
```suggestion
 * An adapter that implements the Core Bot and can be hosted in different cloud environments both public and private.
```

2022-05-05 14:28 UTC, sw-joelmut approved these changes
Besides Ceci commented, it should be good

2022-05-06 18:17 UTC, ceciliaavila approved these changes

2022-05-12 16:40 UTC, sw-joelmut commented
/promoted 4239

2022-05-12 16:40 UTC, closed without merging