Southworks/fix/eslint remaining final issues
southworks/botbuilder-js pull request #305
Opened 2022-05-09 17:57 UTC by erquirogasw

Addresses # 4204
#minor

## Description
This PR fixes the ESLint and JSDoc issues in the botbuilder-connector library.

## Specific Changes
- Applied auto-fixes with yarn lint --fix
	- Fix spacing
	- Fix indentation
	- Add blank line in between comments
- Applied manual fixes for:
	- Missing documentation

## Testing
_Library eslint status_
<img width="162" alt="image" src="https://user-images.githubusercontent.com/64815358/167469230-3f9fd2ce-5e5c-4796-abad-6225165d98b2.png">

_Library tests status_
<img width="147" alt="image" src="https://user-images.githubusercontent.com/64815358/167469195-ffb224f3-f4bd-40fa-892a-01705a300a58.png">

2022-05-09 18:57 UTC, ceciliaavila requested changes

2022-05-09 18:57 UTC, ceciliaavila commented on libraries/botframework-connector/src/auth/connectorFactoryImpl.ts
> +     * @param audience The audience to use for outbound communication. The will vary by cloud environment.
```suggestion
     * @param audience The audience to use for outbound communication. It will vary by cloud environment.
```

2022-05-09 18:57 UTC, ceciliaavila commented on libraries/botframework-connector/src/auth/parameterizedBotFrameworkAuthentication.ts
> + * Parametrized Cloud Environment used to authenticate Bot Framework Protocol network calls within this environment.
```suggestion
 * Parameterized Cloud Environment used to authenticate Bot Framework Protocol network calls within this environment.
```

2022-05-09 18:57 UTC, ceciliaavila commented on libraries/botframework-connector/src/auth/parameterizedBotFrameworkAuthentication.ts
> +     * Creates a ConnectorFactory that can be used to create IConnectorClient that use credentials from this particular cloud environment.
IConnectorClient does not exist in JS.

2022-05-09 18:57 UTC, ceciliaavila commented on libraries/botframework-connector/src/auth/passwordServiceClientCredentialFactory.ts
> +     * @param validateAuthority The validate authority vale to use.
```suggestion
     * @param validateAuthority The validate authority value to use.
```

2022-05-09 18:57 UTC, ceciliaavila commented on libraries/botframework-connector/src/auth/userTokenClientImpl.ts
> +     * A Task<TResult> representing the result of the asynchronous operation.
Tasks are a .NET thing. In JS we have Promises. Also, that should be the return information, not the description of the function.

2022-05-09 18:57 UTC, ceciliaavila commented on libraries/botframework-connector/src/auth/userTokenClientImpl.ts
> +     * @param connectionName Name of the auth connection to use
```suggestion
     * @param connectionName Name of the auth connection to use.
```

2022-05-09 18:57 UTC, ceciliaavila commented on libraries/botframework-connector/src/auth/userTokenClientImpl.ts
> +     * @returns A promise of Array of TokenStatus.
```suggestion
     * @returns A promise with an array of the Token Status.
```

2022-05-09 18:57 UTC, ceciliaavila commented on libraries/botframework-connector/src/auth/userTokenClientImpl.ts
> +     * @param exchangeRequest The exchange request details, either a token to exchange or a uri to exchange
```suggestion
     * @param exchangeRequest The exchange request details, either a token to exchange or a uri to exchange.
```

2022-05-09 19:39 UTC, sw-joelmut requested changes

2022-05-09 19:39 UTC, sw-joelmut commented on libraries/botbuilder-ai-orchestrator/package.json
> +    "botbuilder-dialogs": "4.1.6"
Sort this deps

2022-05-09 19:39 UTC, sw-joelmut commented on libraries/botbuilder-ai-orchestrator/package.json
>    },
Remove empty peer and dev fields.

2022-05-09 19:39 UTC, sw-joelmut commented on libraries/botframework-connector/src/auth/botFrameworkClientImpl.ts
> + */
We could change the `// Internal` comment, adding the `@internal` tag at the beginning of the JSDoc comment. Also add the xref for BotFrameworkClient

2022-05-09 19:39 UTC, sw-joelmut commented on libraries/botframework-connector/src/auth/botFrameworkClientImpl.ts
> +     * @returns Promise with optional invokeResponse.
You could use the one from `botbuilder\src\botFrameworkHttpClient.ts`
`@returns {Promise<InvokeResponse<T>>} A promise representing the asynchronous operation.`

2022-05-09 19:39 UTC, sw-joelmut commented on libraries/botframework-connector/src/auth/connectorFactoryImpl.ts
> + */
Same as mentioned previously

2022-05-09 19:39 UTC, sw-joelmut commented on libraries/botframework-connector/src/auth/parameterizedBotFrameworkAuthentication.ts
> + */
Same as mentioned previously

2022-05-09 19:39 UTC, sw-joelmut commented on libraries/botframework-connector/src/auth/parameterizedBotFrameworkAuthentication.ts
> +     * @param callerId The callerId set on on authenticated [Activities](xref:botframework-schema.Activity).
```suggestion
     * @param callerId The callerId set on an authenticated [Activities](xref:botframework-schema.Activity).
```

2022-05-09 19:39 UTC, sw-joelmut commented on libraries/botframework-connector/src/auth/userTokenClientImpl.ts
> + */
same as mentioned before

2022-05-10 15:30 UTC, ceciliaavila approved these changes

2022-05-10 16:33 UTC, sw-joelmut requested changes

2022-05-10 16:33 UTC, sw-joelmut commented on libraries/botframework-connector/src/auth/botFrameworkClientImpl.ts
> + * Implementation of [BotFrameworkClient](xref:botframework-connector.BotFrameworkClient).
This should be in its own separate line, see other cases in the project. same for the rest
```
/**
 * @internal
 * Implementation of [BotFrameworkClient](xref:botframework-connector.BotFrameworkClient).
```

2022-05-10 16:34 UTC, sw-joelmut commented on libraries/botframework-connector/src/auth/botFrameworkClientImpl.ts
> + * Implementation of [BotFrameworkClient](xref:botframework-connector.BotFrameworkClient).
Also ensure the PR checks are passign successfully

2022-05-12 14:04 UTC, sw-joelmut approved these changes

2022-05-12 14:26 UTC, sw-joelmut approved these changes

2022-05-12 16:41 UTC, sw-joelmut commented
/promoted 4240

2022-05-12 16:41 UTC, closed without merging