fix: [#4400] Security vulnerabilityCVE-2022-23540, CVE-2022-23539, CVE-2022-23541, CVE-2022-23529
southworks/botbuilder-js pull request #337
Opened 2023-01-10 18:16 UTC by erquirogasw

Fixes # 4400
#minor

## Description
This PR fixes the vulnerability alerts related to the **jsonwebtoken** version.

## Specific Changes
Updated _@azure/msal-node_ to **1.14.6** in yarn.lock file.

## Testing
Alerts don't appear after the update.
![image](https://user-images.githubusercontent.com/64815358/211630467-94703076-f6e2-4161-acd9-170c7e7cf177.png)

2023-01-13 16:37 UTC, ceciliaavila requested changes

2023-01-13 16:37 UTC, ceciliaavila commented on yarn.lock
> +  version "2.1.0"
I think these changes belong to the previous approach you took. I would take the yarn.lock in main branch and execute the install again to commit only the jsonwebtoken related changes.

2023-01-13 19:32 UTC, ceciliaavila approved these changes

2023-01-16 13:25 UTC, sw-joelmut approved these changes

2023-01-16 13:56 UTC, erquirogasw commented
/promoted 4409

2023-01-16 13:56 UTC, closed without merging