Southworks/add/cosmosdbpartitionedstorage tokencredential
southworks/botbuilder-js pull request #346
Opened 2023-05-03 13:35 UTC by JhontSouth

Fixes #minor

## Description
This PR adds the _CosmosDB_ authentication method through _TokenCredential_ in _CosmosDbPartitionedStorage_

## Specific Changes
- Upgraded _@azure/cosmos_ package from ^3.3.1 to ^3.10.0 to get the _CosmosClient_ constructor that uses _TokenCredential_.
- Added _TokenCredential_ property to _CosmosDbPartitionedStorageOptions_ class.
- Updated validation to throw an error if _AuthKey_ and _TokenCredential_ properties are null.
- Added the alternative to create a _CosmosClient_ using the _TokenCredential_ if provided.
- Updated _Typescript_ version to avoid errors  with the new version of _@azure/cosmos_

## Testing
The following image shows the information saved in CosmosDB after creating the client using Azure credentials.
![image](https://user-images.githubusercontent.com/122501764/235931203-4e0039d1-f8b7-49ba-a6eb-103caa6b0b05.png)

2023-05-04 13:23 UTC, sw-joelmut requested changes
I think the `err: any` are ok, another solution could have been supporting the `unknown` type in most cases like `Error | unknown`, but it's ok.

2023-05-04 13:23 UTC, sw-joelmut commented on libraries/botbuilder-azure/package.json
> +}
Add the end of line (EOF).

2023-05-04 13:23 UTC, sw-joelmut commented on package.json
> +}
Add the end of line (EOF).

2023-05-04 13:32 UTC, ceciliaavila requested changes
Add the issue number in the PR title and in the description remove the `^` from the new cosmos package version.

2023-05-04 13:58 UTC, ceciliaavila approved these changes

2023-05-04 14:59 UTC, sw-joelmut approved these changes
Just a reminder that when we promote the PR add the issue number in the Fixes # xxx description

2023-05-05 13:30 UTC, ceciliaavila commented
/promoted 4473

2023-05-05 13:30 UTC, closed without merging