[#4446] Azure Blob Storage should support Identity authentication
southworks/botbuilder-js pull request #352
Opened 2023-06-02 16:41 UTC by JhontSouth

#minor

## Description
This PR allows using the MSI authentication for Azure Blob Storage.

## Specific Changes
  - Added a new option in the constructor with the necessary parameters for creating the blob storage client using a msi credentials.

## Testing
The following image shows the new validations and unit test passing.
![image](https://github.com/southworks/botbuilder-js/assets/122501764/cc0ed518-ebb2-45ed-b5b9-1f0dd6613f83)

2023-06-02 19:48 UTC, ceciliaavila requested changes

2023-06-02 19:48 UTC, ceciliaavila commented on libraries/botbuilder-azure-blobs/src/blobsStorage.ts
> +function isCredentialType(value: any): value is TokenCredential {
There's a method we can use in TokenCredential to check this.
![image](https://github.com/southworks/botbuilder-js/assets/44245136/d495dded-b71f-429e-8ea8-092efbc1044b)

2023-06-02 19:48 UTC, ceciliaavila commented on libraries/botbuilder-azure-blobs/src/blobsStorage.ts
> +        options?: BlobsStorageOptions
The new parameters should be the last ones, to avoid breaking changes.

2023-06-06 18:10 UTC, ceciliaavila approved these changes

2023-06-06 18:51 UTC, erquirogasw approved these changes

2023-06-06 20:40 UTC, ceciliaavila commented
/promoted 4486

2023-06-06 20:40 UTC, closed without merging