fix: [#4509] botbuilder-ai@4.20.0 is still installing @azure/ms-rest-js@1.11.2 for @azure/cognitiveservices-luis-runtime
southworks/botbuilder-js pull request #365
Opened 2023-08-16 13:12 UTC by ceciliaavila

Fixes # 4509
#minor

## Description
This PR upgrades `@azure/cognitiveservices-luis-runtime` to v.4.0.0 in `botbuilder-ai` to avoid the use of the _tough-cookie_ package due to its [vulnerability issue](https://github.com/advisories/GHSA-72xf-g2v4-qvf3).
As version 4.0.0 introduced several breaking changes, we added the `luisV2-models` folder with the interfaces and classes that are required for the v2 runtime to work.

## Specific Changes
  - Upgrades `@azure/cognitiveservices-luis-runtime` package from version 2.0.0 to version 4.0.0
  - Created the folder `luisV2-models` containing the following interfaces and classes missing in the new version of the package:
     - LuisResult
     - LuisMappers
     - LuisParameters
     - LuisPrediction
     - LUISRuntimeClientV2
  - Updated `luisSdk.test.js` unit tests to work with the new `LUISRuntimeClientV2`.

## Testing
This image shows the unit tests passing after the upgrade.
![image](https://github.com/southworks/botbuilder-js/assets/44245136/e416ecc4-be7d-4ca4-83ea-9ef91229c747)

2023-08-16 17:47 UTC, JhontSouth approved these changes

2023-08-16 19:54 UTC, sw-joelmut requested changes
just small things, nice work

2023-08-16 19:54 UTC, sw-joelmut commented on libraries/botbuilder-ai/src/luisV2-models/luisResult.ts
> +    topScoringIntent?: IntentModel;
Should this prop have doc?

2023-08-16 19:54 UTC, sw-joelmut commented on libraries/botbuilder-ai/src/luisV2-models/luisResult.ts
> +    connectedServiceResult?: LuisResult;
same here

2023-08-16 19:54 UTC, sw-joelmut commented on libraries/botbuilder-ai/src/luisV2-models/luisRuntimeClientV2.ts
> + */
Here it has empty doc

2023-08-16 20:31 UTC, ceciliaavila commented on libraries/botbuilder-ai/src/luisV2-models/luisResult.ts
> +    topScoringIntent?: IntentModel;
I added the missing doc. Thanks!

2023-08-17 12:33 UTC, sw-joelmut approved these changes

2023-08-17 13:12 UTC, ceciliaavila commented
/promoted 4519

2023-08-17 13:12 UTC, closed without merging