fix: remove ms-rest package
southworks/botbuilder-js pull request #366
Opened 2023-08-16 16:08 UTC by JhontSouth

Fixes #

## Description

## Specific Changes

  - 
  -
  -

## Testing

2023-08-16 20:11 UTC, sw-joelmut requested changes
I used this to compare it "https://github.com/southworks/botbuilder-js/compare/southworks/update/remove-ms-rest-azure...southworks:botbuilder-js:southworks/update/remove-ms-rest" since i noticed there were similar changes to the ms-rest-azure ones.

Just a little thing, there are a few .d.ts files that continue having ms-rest, i think we should update them, i think running the build? or something for these types.

2023-08-18 13:12 UTC, sw-joelmut approved these changes

2023-08-18 14:24 UTC, ceciliaavila approved these changes

2023-08-18 14:28 UTC, ceciliaavila commented
/promoted 4523

2023-08-18 14:28 UTC, closed without merging