port:[#6677][#4530] Add support for meeting participants added/removed events
southworks/botbuilder-js pull request #372
Opened 2023-09-11 16:59 UTC by JhontSouth

#minor

## Description
This PR adds support to _TeamsActivityHandler_ for meeting participants join/leave events.

## Specific Changes
- Added support for 2 new activity types - `application/vnd.microsoft.meetingParticipantJoin` and `application/vnd.microsoft.meetingParticipantLeave`.
- Added functions to register handlers for when teams meeting participants are joined/left.
- Added unit tests for every case.

## Testing
This image shows the implementation tested with a sample.
![image](https://github.com/southworks/botbuilder-js/assets/122501764/6d0e59cb-b997-42ea-8870-a27c1d27b9b8)

2023-09-18 13:58 UTC, sw-joelmut requested changes

2023-09-18 13:58 UTC, sw-joelmut commented on libraries/botbuilder/tests/teamsActivityHandler.test.js
> +                value: JSON.parse('{ "lastReadMessageI": 10101010}'),
Is this on purpose? the `d` got deleted

2023-09-18 14:02 UTC, sw-joelmut commented on libraries/botbuilder/tests/teamsActivityHandler.test.js
> +                value: JSON.parse('{ "lastReadMessageI": 10101010}'),
Also, the test-compat pipeline is failing

2023-09-20 12:47 UTC, ceciliaavila requested changes

2023-09-20 12:47 UTC, ceciliaavila commented on libraries/botbuilder/src/teamsActivityHandler.ts
> +     */
```suggestion
     * Invoked when a Meeting Participant Leave event activity is received from the connector.
     * Override this in a derived class to provide logic for when a meeting participant is left.
     *
     * @param context The context for this turn.
     * @returns A promise that represents the work queued.
     */
```

2023-09-20 12:47 UTC, ceciliaavila commented on package.json
> -    "lint": "wsrun -m -l lint --max-warnings=0",
Don't push this change.

2023-09-20 16:38 UTC, ceciliaavila approved these changes

2023-09-21 12:35 UTC, sw-joelmut approved these changes

2023-09-21 13:13 UTC, ceciliaavila commented
/promoted 4538

2023-09-21 13:13 UTC, closed without merging