[#4470] Migrate off @azure/ms-rest-js
southworks/botbuilder-js pull request #376
Opened 2023-10-31 13:41 UTC by JhontSouth

#minor

## Description
This PR replaces the uses of **_@azure/ms-rest-js_** in the following botbuilder-js libraries.

- [ ] botbuilder
- [ ] botbuilder-ai
- [ ] botframework-connector
- [ ] tool

## Specific Changes
  - Replaced the **_@azure/ms-rest-js_** imports with **_@azure/core-http_**.
  - Added **_@azure/core-http_** to libraries package.json.

## Testing
The following image shows some samples working after the update.
![image](https://github.com/southworks/botbuilder-js/assets/122501764/44ada9a4-ee05-4bef-859b-f7d1122a06ac)
![image](https://github.com/southworks/botbuilder-js/assets/122501764/62c877d0-5cdb-4067-bf2b-ca3798a3f08f)

2023-11-01 15:52 UTC, ceciliaavila requested changes

2023-11-01 15:52 UTC, ceciliaavila commented on package.json
I think this change should be in the last PR to avoid the checks to fail.

2023-11-01 16:11 UTC, JhontSouth commented on package.json
this is the main PR, I'll create the other PR's pointing to this one

2023-11-01 17:23 UTC, ceciliaavila commented on package.json
Mmm...ok, then you should check why the pipelines are failing.

2023-11-03 17:26 UTC, ceciliaavila requested changes

2023-11-03 17:26 UTC, ceciliaavila commented on libraries/botframework-connector/src/connectorApi/connectorClient.ts
> +import { ServiceClientCredentials } from "@azure/core-http"
Use single quotes for the import.

2023-11-03 17:26 UTC, ceciliaavila commented on libraries/botframework-connector/src/connectorApi/operations/conversations.ts
> +              className: "ChannelAccount"
What happened with the indentation? Is the new one correct?

2023-11-03 17:26 UTC, ceciliaavila commented on libraries/botframework-connector/src/tokenApi/operations/userToken.ts
> +import { ServiceCallback, RequestOptionsBase, Serializer, OperationSpec } from "@azure/core-http";
Use single quotes here.

2023-11-03 17:26 UTC, ceciliaavila commented on libraries/tests.uischema
> +        "dialogs"
What's this change about?

2023-11-03 17:58 UTC, JhontSouth commented on libraries/tests.uischema
> +        "dialogs"
to avoid errors with test:schema

2023-12-01 18:12 UTC, sw-joelmut requested changes

2023-12-01 18:12 UTC, sw-joelmut commented on package.json
> +    "@azure/core-util": "1.5.0"
Same here

2023-12-04 16:59 UTC, ceciliaavila approved these changes

2023-12-04 17:31 UTC, JhontSouth commented
Promoted /4578

2023-12-04 17:31 UTC, closed without merging