fix: [#4470] Migrate off @azure/ms-rest-js botbuilder-ai
southworks/botbuilder-js pull request #382
Opened 2023-11-02 15:40 UTC by JhontSouth

#minor

## Description
This PR replaces the uses of **_@azure/ms-rest-js_** in the following botbuilder-js libraries.

- [ ] botbuilder
- [x] botbuilder-ai
- [ ] botframework-connector
- [ ] tool

## Specific Changes
  - Replaced the **_@azure/ms-rest-js_** imports with **_@azure/core-http_**.
  - Added **_@azure/core-http_** to libraries package.json.
  - Added **_@azure/core-util_** version 1.5.0 to resolutions.
  - Updated unit tests to work with core-http **_RestError_**.

## Testing
The following image shows some samples working after the update.
![image](https://github.com/southworks/botbuilder-js/assets/122501764/44ada9a4-ee05-4bef-859b-f7d1122a06ac)
![image](https://github.com/southworks/botbuilder-js/assets/122501764/62c877d0-5cdb-4067-bf2b-ca3798a3f08f)

2023-11-03 17:36 UTC, ceciliaavila requested changes

2023-11-03 17:36 UTC, ceciliaavila commented on libraries/botbuilder-ai/src/luisRuntimeClientContext.ts
> + */
I think we should remove this comment. It's not an autogenerated code.

2023-11-03 17:36 UTC, ceciliaavila commented on libraries/botbuilder-ai/src/luisV2-models/sentiment.ts
> + */
same here.

2023-11-03 17:36 UTC, ceciliaavila commented on libraries/botbuilder-ai/src/luisV2-models/sentiment.ts
Is correct to name this file sentiment? It contains a lot of other interfaces.

2023-11-03 18:00 UTC, JhontSouth commented on libraries/botbuilder-ai/src/luisV2-models/sentiment.ts
I'm extracting the logic and name from _@azure/cognitiveservices-luis-runtime_

2023-12-01 18:07 UTC, sw-joelmut requested changes

2023-12-04 16:20 UTC, sw-joelmut approved these changes

2023-12-04 17:00 UTC, ceciliaavila approved these changes

2023-12-04 17:29 UTC, JhontSouth commented
Promoted /4577

2023-12-04 17:29 UTC, closed without merging