fix: Add chromedriver binary in its updated version
southworks/botbuilder-js pull request #395
Opened 2024-01-05 16:49 UTC by JhontSouth

#minor

## Description
This PR avoids the Command Injection vulnerability by removing the _**chromedriver**_ package and replaces its functionality using its binary to perform the browser unit tests.

## Specific Changes
  - Removed  _**chromedriver**_ package from browser-functional tests.
  - Added _**chromedriver**_ binary into browser-functional.
  - Modified server path of _nigthwatch_ chrome configuration.
  - Removed unnecessary jobs related to _**chromedriver**_ in the _browser-tests-build-ci_ pipeline.

## Testing
The following image shows the _browser-tests-build-ci_ pipeline running successfully after the changes.
![image](https://github.com/southworks/botbuilder-js/assets/122501764/d06885ad-159a-453b-8581-1c7a086025a0)

2024-01-05 20:23 UTC, ceciliaavila requested changes
Check the PR's tittle. Bump would mean a version upgrade. I think we should use fix and explain in the description that this PR changes are meant to avoid a vulnerability.
NIT: remove the final dot from the title.

2024-01-08 17:47 UTC, ceciliaavila approved these changes

2024-01-08 19:06 UTC, sw-joelmut approved these changes

2024-01-08 19:06 UTC, sw-joelmut commented on testing/browser-functional/nightwatch.conf.js
> +            silent: true,
I dont know about this extends selenium, are we sure we are not missing some functionality? or that extends selenium is the new selenium: {
                start_process: false,
            }?

2024-01-09 14:54 UTC, JhontSouth commented
Promoted /4596

2024-01-09 14:54 UTC, closed without merging