fix CVE-2020-8203 with lodash.pick (High)
southworks/botbuilder-js pull request #431
Opened 2024-06-21 16:48 UTC by andres-robinet-sw

Addresses # #4684
#minor

## Description
This PR updates the version of **lodash.pick** and fixes the [CVE-2020-8203](https://github.com/advisories/GHSA-p6mc-m468-83gw) vulnerability.
There is no patch for [lodash.pick@4.4.0](https://www.npmjs.com/package/lodash.pick/v/4.4.0) which is a dependency of [nightwatch@2.6.21](https://www.npmjs.com/package/nightwatch/v/2.6.21).
[Per Method Packages](https://lodash.com/per-method-packages) are discouraged by **lodash** and [nightwatch@3.4.0](https://www.npmjs.com/package/nightwatch/v/3.4.0) fixes this.
However, there's a transitive dependency with [jsdom@23.1.0](https://www.npmjs.com/package/jsdom/v/23.1.0) which restricts Node engines to `>=18`.
Thus, we need to force a fully patched version of **lodash** to replace **lodash.pick**.

## Specific Changes
  - Added resolution for **lodash.pick** to [lodash@4.17.21](https://www.npmjs.com/package/lodash/v/4.17.21)

## Testing
The following screenshot shows the updated version for the **lodash.pick** package.
![image](https://github.com/southworks/botbuilder-js/assets/64077347/0579d941-69a5-4052-af44-05ee6a3102cb)

2024-06-24 16:47 UTC, JhontSouth approved these changes

2024-06-25 15:23 UTC, sw-joelmut requested changes

2024-06-25 15:23 UTC, sw-joelmut commented on package.json
> +    "lodash.pick": "https://github.com/lodash/lodash/archive/refs/tags/4.17.21.tar.gz"
We could use `npm:` like in this pr https://github.com/southworks/botbuilder-js/pull/433/files.

2024-06-25 15:23 UTC, sw-joelmut commented on package.json
> +    "lodash": "4.17.21",
lodash doesnt seem to be necessary in the resolutions, its being fixed in another pr, merge main changes and validate

2024-06-25 16:57 UTC, sw-joelmut approved these changes

2024-06-25 18:22 UTC, andres-robinet-sw commented
/promoted 4692

2024-06-25 18:22 UTC, closed without merging