fix: CVE-2024-42460 vulnerability with elliptic
southworks/botbuilder-js pull request #458
Opened 2024-08-19 16:51 UTC by JhontSouth

#minor

## Description
This PR updates the _**elliptic**_ version to 6.5.7 to avoid the [CVE-2024-42460](https://github.com/advisories/GHSA-977x-g7h5-7qgw) vulnerability.

## Specific Changes
  - Updated _elliptic_ to version 6.5.7 in _yarn.lock_ file.

## Testing
The following image shows the _elliptic_ version installed.
![image](https://github.com/user-attachments/assets/fed504c1-0d73-4778-9030-2f2496bdc042)

2024-08-19 18:25 UTC, ceciliaavila requested changes
There's another yarn.lock resolving the vulnerable version of this package: https://github.com/southworks/botbuilder-js/blob/main/testing/browser-functional/browser-echo-bot/yarn.lock#L4112

2024-08-19 19:44 UTC, JhontSouth commented
> There's another yarn.lock resolving the vulnerable version of this package: https://github.com/southworks/botbuilder-js/blob/main/testing/browser-functional/browser-echo-bot/yarn.lock#L4112

solved, thank you

2024-08-19 19:48 UTC, ceciliaavila approved these changes

2024-08-20 12:51 UTC, sw-joelmut approved these changes

2024-08-26 14:38 UTC, JhontSouth commented
Promoted /4729

2024-08-26 14:38 UTC, closed without merging