fix: ESLint issues in bobuilder-core
southworks/botbuilder-js pull request #489
Opened 2024-10-21 19:31 UTC by JhontSouth

#minor

## Description
This PR fixes all the new errors and warnings incoming in the latest version of ESLint packages

## Specific Changes
  - Added missing params documentation in some methods.
  - Formatted with required spaces and comment lines required by ESLint,
  - Lint command pointing to main ESLint config file.

## Testing
The following image shows the lint command running without problems in _botbuilder-core_.
![image](https://github.com/user-attachments/assets/14bd7766-1897-4c7d-bee6-56cecae97c9b)

2024-10-24 12:14 UTC, ceciliaavila requested changes
Please update with base branch's latest changes

2024-10-25 14:03 UTC, sw-joelmut requested changes

2024-10-28 14:57 UTC, JhontSouth commented on libraries/botbuilder-core/src/botStatePropertyAccessor.ts
> +     */
fixed

2024-10-28 15:20 UTC, JhontSouth commented on libraries/botbuilder-core/src/botStatePropertyAccessor.ts
> -     * @param defaultValue (Optional) default value to copy to the backing storage object if the property isn't found.
the parameter is not in that method

2024-10-28 15:25 UTC, ceciliaavila commented on libraries/botbuilder-core/src/botStatePropertyAccessor.ts
> -     * @param defaultValue (Optional) default value to copy to the backing storage object if the property isn't found.
Oh, it's true, I've got confused with the one below. Thanks!

2024-10-28 15:25 UTC, ceciliaavila approved these changes

2024-10-28 15:47 UTC, sw-joelmut approved these changes

2024-12-20 16:35 UTC, JhontSouth commented
Promoted /4827

2024-12-20 16:35 UTC, closed without merging