fix: [#4684] ESLint issues in botbuilder-dialogs-adaptive
southworks/botbuilder-js pull request #492
Opened 2024-10-22 20:35 UTC by sw-joelmut

Addresses # 4684
#minor

## Description
This PR fixes all the new ESLint errors and warnings that appeared after the ESLint packages' upgrade in the botbuilder-dialogs-adaptive project.

## Specific Changes
  - Removed 'only-warn' plugin from 'botbuilder-dialogs-adaptive/eslint.config.cjs' and its dependency.
  - All updated TS and JS files were due to prettier, mocha and jsdoc new rules.

## Testing
The following image shows that there are no more ESLint issues.
![image](https://github.com/user-attachments/assets/89d6889d-2025-4760-af40-773d94aa4475)

2024-10-23 16:10 UTC, ceciliaavila requested changes

2024-10-23 16:10 UTC, ceciliaavila commented on libraries/botbuilder-dialogs-adaptive/src/actions/httpRequest.ts
> +
I think this line can be removed.

2024-10-23 18:26 UTC, sw-joelmut commented on libraries/botbuilder-dialogs-adaptive/src/actions/httpRequest.ts
> +
applied thanks!

2024-10-23 19:05 UTC, ceciliaavila approved these changes

2024-12-20 13:09 UTC, sw-joelmut commented
/promoted 4826

2024-12-20 13:09 UTC, closed without merging