fix: [#4684] ESLint issues in botbuilder-ai
southworks/botbuilder-js pull request #496
Opened 2024-10-23 19:35 UTC by ceciliaavila

Addresses # 4684
#minor

## Description
This PR fixes the new ESLint errors and warnings after upgrading the ESLint packages in the _botbuilder-ai_ project.

## Specific Changes
  - Removed the 'only-warn' plugin from 'botbuilder-ai/eslint.config.cjs' and its dependency.
  - Applied the auto fix flag for most issues (spacing, trailing commas, indentation, and removal of unnecessary eslint exceptions). 
  - Applied manual fixes for new rules like 'no-constant-binary-expression'.

## Testing
The following images show the number of issues fixed in the library.
![image](https://github.com/user-attachments/assets/31db3c9c-3068-4cbb-8476-5e6a12b3b0ca)

2024-10-23 20:15 UTC, sw-joelmut requested changes

2024-10-23 20:15 UTC, sw-joelmut commented on libraries/botbuilder-ai/eslint.config.cjs
Since there is no reason to have this config, we should reference it in the lint script like "eslint . --config ../../eslint.config.cjs"

2024-10-23 20:31 UTC, ceciliaavila commented on libraries/botbuilder-ai/eslint.config.cjs
Done. Thanks!

2024-10-24 12:46 UTC, sw-joelmut approved these changes

2024-10-28 15:18 UTC, JhontSouth approved these changes

2024-11-08 19:01 UTC, ceciliaavila commented
/promoted 4790

2024-11-08 19:01 UTC, closed without merging