fix: ESLint issues in botbuilder-azure-queues
southworks/botbuilder-js pull request #505
Opened 2024-10-24 19:23 UTC by JhontSouth

Addresses # 4684
#minor

## Description
This PR fixes the new errors and warnings incoming in the latest version of ESLint packages in _botbuilder-azure-queues_.

## Specific Changes
  - Removed _eslint.config.cjs_ file.
  - Fixed ESLint issues by running _--fix_ flag.

## Testing
The following image shows the lint command running without problems in _botbuilder-azure-queues_.
![image](https://github.com/user-attachments/assets/a270c35b-bc5d-4d03-876d-8ad99a1cb16c)

2024-10-25 19:11 UTC, ceciliaavila requested changes

2024-10-25 19:11 UTC, ceciliaavila commented on libraries/botbuilder-azure-queues/package.json
Remove the eslint-plugin-only-warn package

2024-10-28 16:07 UTC, JhontSouth commented on libraries/botbuilder-azure-queues/package.json
fixed

2024-10-28 17:56 UTC, ceciliaavila approved these changes

2024-12-20 17:27 UTC, JhontSouth commented
Promoted /4831

2024-12-20 17:27 UTC, closed without merging