feat: Update versions for generators
southworks/botbuilder-js pull request #524
Opened 2024-11-14 12:46 UTC by ceciliaavila

#minor

## Description
This PR includes the generators' templates to be updated by the **_update-versions_** script by including them in the _workspaces_ list.
It also updates the versions in the _package.json_ file to match the one used in the libraries (4.1.6) and upgrades some dependencies in the TS bots to fix errors found when building the generated bots.

## Specific Changes
- Changed botbuilder dependencies' version to 4.1.6 in all bots' templates.
- Updated TS bots by adding the _types/node_ package and upgrading _typescript_ dependency to version 4.9.3. Also, updated _tsconfig_ files updating the _module_ and adding _moduleResolution_ and _esModuleInterop_ properties.
- Added the _'generators/generator-botbuilder/generators/app/templates/'_ path to workspaces in the _package.json_ file.
- Updated _updateVersions_, _workspace_, and _package_ files to include the new projects in the script.

## Testing
These images show the updated version in the bots and the bots working with the changes.
![image](https://github.com/user-attachments/assets/62d501c0-b893-42cf-b9ab-798da2b46d31)
![image](https://github.com/user-attachments/assets/2d58e818-055e-4158-aa88-8663cf381b4e)

2024-11-14 14:08 UTC, JhontSouth approved these changes

2024-11-19 12:57 UTC, sw-joelmut requested changes

2024-11-19 12:57 UTC, sw-joelmut commented on libraries/botbuilder-repo-utils/src/updateVersions.ts
> +        const workspaces = await collectWorkspacePackages(repoRoot, projects);
indentation

2024-11-19 13:48 UTC, ceciliaavila commented on libraries/botbuilder-repo-utils/src/updateVersions.ts
> +        const workspaces = await collectWorkspacePackages(repoRoot, projects);
Fixed. Thanks!

2024-11-19 14:09 UTC, sw-joelmut approved these changes

2024-11-19 17:06 UTC, ceciliaavila commented
/promoted 4796

2024-11-19 17:06 UTC, closed without merging